### ISSUE TITLE
VirtualKernel in bin/console

### ISSUE THREAD

**Issue by alterphp** [yceruto/symfony-ddd-skeleton#11]
Hello @yceruto !

Just wondering if `bin/console` is working with `\VirtualKernel` at lines 46 and 102. I expected `App\Virtual\Kernel` (or a use statement) ?

**Comment by yceruto** [comment]
Hi! not sure about the lines ref, but yes, it's working right now. 

The `\VirtualKernel` is a mapped class:
https://github.com/yceruto/symfony-skeleton-vkernel/blob/5d0558fc2610832dbe3ac2e212a4c9730e3d1f62/composer.json#L22-L29

it shouldn't be under any namespace, because it belong to all apps under `src/`.

Have you updated the repository lately?

**Comment by alterphp** [comment]
My mistake, we use it under App namespace that is a no-sense. We just updated a project to Symfony 4.2/3 structure for root controllers (bin/console, public/index.php and so on) that's why we came back to the repo and take the related updates ;-)
